version: '3.8'
services:
  cours-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/cours-enfants"
      JWT_SECRET: "votre_secret_jwt"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
